### ISSUE TITLE
405 error.. looks like malformed request url

### ISSUE THREAD

**Issue by str3tch** [serverless/serverless-graphql-apollo#101]
hey

I've followed the instructions and deployed to production, but when I view it, there's a 405 error for the POST to the lambda endpoint. It doesn't look correct, see here:

![image](https://user-images.githubusercontent.com/1896276/29111416-bc3137b2-7d1c-11e7-99b4-2a152e99c29b.png)

I set the URL in security.env.prod correctly I think?

`URL="https://k6e3zyqa61.execute-api.us-east-1.amazonaws.com/production/graphql"`

What am I doing wrong?

cheers!

**Comment by david-potgieter** [comment]
hey @str3tch - not sure if you have fixed it, but remove the `"`, so:
`URL=https://k6e3zyqa61.execute-api.us-east-1.amazonaws.com/production/graphql` < - should work.

**Comment by sid88in** [comment]
@str3tch is this issue resolved? We have updated this repo. can you please try again?

**Comment by sid88in** [comment]
Your apollo client must have the right remote URL.
