### ISSUE TITLE
Changes needed after rewrite

### ISSUE THREAD

**Issue by nikgraf** [serverless/serverless-graphql-apollo#103]
@sid88in in case you pick one best to put your name next to the task before getting started. This way we don't work on the same things. 

- [x] move `app-server` to root and rename to `app-backend` (Sid: https://github.com/serverless/serverless-graphql-apollo/pull/109)
- [x] remove express (Nik: https://github.com/serverless/serverless-graphql-apollo/pull/104)
- [x] remove command `npm run build:node_modules` and update the readme (Sid https://github.com/serverless/serverless-graphql-apollo/pull/109)
- [x] add graphiQL (Sid https://github.com/serverless/serverless-graphql-apollo/pull/111)
- [x] remove style linting (Nik: https://github.com/serverless/serverless-graphql-apollo/pull/105)
- [x] remove optional serverless.yml `integration: lambda-proxy` (Nik: https://github.com/serverless/serverless-graphql-apollo/pull/106)
- [x] remove postcss, nodemon, lint-staged, jest-cli, express, apollo-server-express (Nik: https://github.com/serverless/serverless-graphql-apollo/pull/105)
- [x] investigate how to pass config to front-end https://github.com/serverless/serverless-graphql-apollo/pull/102/files#diff-b5eb2c0ee2bba7821aa7b46676f0a92eR13 (Sid)
- [ ] re-add instructions how to deploy the front-end (old: https://github.com/serverless/serverless-graphql-apollo/pull/102/files#diff-088b1df4393822806126ddcf7e2cfec2L19) (Nik)
- [x] lock frameworkVersion: ">=1.5.0 <2.0.0" (Nik: https://github.com/serverless/serverless-graphql-apollo/pull/106)
- [x] decide to either use yarn or npm (not both) (Sid: https://github.com/serverless/serverless-graphql-apollo/pull/109)
- [x] update .gitignore to ignore for `config.js` and `.webpack` (Nik: https://github.com/serverless/serverless-graphql-apollo/pull/106)
- [x] can we remove .babelrc because the info is defined in the webpack babel loader? (Nik https://github.com/serverless/serverless-graphql-apollo/pull/107)

Related PR: https://github.com/serverless/serverless-graphql-apollo/pull/102

**Comment by sid88in** [comment]
https://www.sitepoint.com/yarn-vs-npm/ looks like yarn wins here

**Comment by nikgraf** [comment]
@sid88in this analysis is outdated since npm has lockfiles as well now. Nevertheless it's fine to go with yarn from my perspective

**Comment by sid88in** [comment]
above task to figure out configs should eventually address https://github.com/serverless/serverless-graphql-apollo/pull/126

**Comment by sid88in** [comment]
@nikgraf 90% of the issues were completed in this list except - re-add instructions how to deploy the front-end. As we discussed we are going to add front-end options for production deployment, so going to create a separate issue for that.
