### ISSUE TITLE
Write Resolvers for REST API, DynamoDB, Lambda 

### ISSUE THREAD

**Issue by sid88in** [serverless/serverless-graphql-apollo#112]

**Comment by nikgraf** [comment]
I was thinking about something simple e.g. a Weather App to manage your favourite cities and receive weather information for that.

- There could be a query resolver just returning with cities the user can select (this list could be a simple JSON).
- One more query resolver would be a wrapper around a real weather HTTP endpoint to fetch weather data for a city.
- Then there could be one mutation where users can create list of favourite cities and the user gets back an ID.
- One more query resolver to fetch the list of cities for an ID (this also could include pagination).

At this point I would recommend to leave out RDS. If RDS is running in a VPC there are some AWS networking issues and a cold-start can take up to 10 seconds. At least it was the case a few months back. In addition without RDS I'm happy to host a demo, but hosting RDS just for a demo is a bit expensive.

What do you think?

**Comment by sid88in** [comment]
thanks @nikgraf sounds good to me.

**Comment by sid88in** [comment]
@nikgraf I suggest we take twitter use case (its more generic and scalable). What say!? Plus there must be some rest endpoints we can wrap graphql around them as well.

For now I have written resolver to wrap existing REST ENDPOINT and will add to master in coming days!

**Comment by sid88in** [comment]
@nikgraf https://github.com/serverless/serverless-graphql-apollo/pull/134 addresses this ticket
