### ISSUE TITLE
DynamoDB Integration with Serverless Offline

### ISSUE THREAD

**Issue by sid88in** [serverless/serverless-graphql-apollo#122]
Reference: 
https://www.npmjs.com/package/serverless-dynamodb-local

**Comment by sid88in** [comment]
@nikgraf I played with this and was able to get some headway! One problem is that I am not 100% clear in case of API Gateway + Proxy to Dynamo DB how to simulate this locally. I was able to insert data in dynamo db locally but was confused on how to simulate API Gateway (my API Gateway has a proxy to dynamodb in request mapping template)

**Comment by nikgraf** [comment]
@sid88in from what I understand there is no need to do any integration. You just need to instantiate a different document storage location as described here https://github.com/99xt/serverless-dynamodb-local#using-dynamodb-local-in-your-code

**Comment by sid88in** [comment]
hmm..maybe. For example: we can create API Gateway with Dynamo Proxy as described here: https://aws.amazon.com/blogs/compute/using-amazon-api-gateway-as-a-proxy-for-dynamodb/

So, now we create dynamo db on local and insert data (everything is good) but next step is to hit this API and fetch data from local dynamodb. I'll do some testing (didn't spend much time on this)

**Comment by sid88in** [comment]
https://github.com/serverless/serverless-graphql-apollo/pull/163/files closed this PR. Dynamodb integration tested
