### ISSUE TITLE
bug: backend `/graphiql` fails

### ISSUE THREAD

**Issue by Birowsky** [serverless/serverless-graphql-apollo#127]
As things currently are, I cannot work with the `graphiql` interface from the backend. Didn't touch anything in the codebase, just ran: `yarn run start-server-lambda:offline`

<img width="1440" alt="screen shot 2017-09-28 at 15 35 44" src="https://user-images.githubusercontent.com/3199950/30969448-b3eb0c96-a462-11e7-962f-07ebdbfc0405.png">

<img width="1440" alt="screen shot 2017-09-28 at 15 38 10" src="https://user-images.githubusercontent.com/3199950/30969572-0f417f62-a463-11e7-953b-0e2ae47f4439.png">

**Comment by sid88in** [comment]
@Birowsky https://github.com/serverless/serverless-graphql-apollo/pull/126 should address this

**Comment by Birowsky** [comment]
@sid88in looks like

**Comment by nileshdt** [comment]
Thanks @sid88in
