### ISSUE TITLE
Enable Lambda functions to be written in ESNext

### ISSUE THREAD

**Issue by brettstack** [serverless/serverless-graphql-apollo#13]
Since we're allowing our client to be written in ES6, we should allow it for lambda functions also.

As described here http://www.rricard.me/es6/aws/lambda/nodejs/2015/11/29/es6-on-aws-lambda.html. Example repo here https://github.com/rricard/lambda-es6-example.

**Comment by nikgraf** [comment]
The current version allows to write you code in ES2015 🙌
