### ISSUE TITLE
GraphQL Playground loading error

### ISSUE THREAD

**Issue by JstnEdr** [serverless/serverless-graphql-apollo#191]
I'm getting a couple errors while trying to access the GraphQL Playground. I've replicated this error with a modified project, as well as a new clone of the repo. 

After following the instructions to get the app running locally, I go to http://localhost:4000/playground and see "Loading GraphQL Playground" in the browser. The console has two errors: `Failed to load resource: net::ERR_CONTENT_DECODING_FAILED` and `Uncaught ReferenceError: GraphQLPlayground is not defined`. 

The first error is referencing middleware.js here: `http://cdn.jsdelivr.net/npm/graphql-playground@1.1.2/build/static/js/middleware.js` but I think it should be an https url instead, like this: `https://cdn.jsdelivr.net/npm/graphql-playground@1.1.2/build/static/js/middleware.js` 

I was unable to find where this is being called in the repo. Any advice?

**Comment by sid88in** [comment]
hey @JstnEdr thanks for reporting it. It might be because of 

1) https://github.com/serverless/serverless-graphql-apollo/issues/136 - the npm package for graphql playground has changed. 

2) We have been actively making changes since yesterday and that might have broken something.

I'll try best to get to the bottom by tonight! If you find the solution, feel free to submit a PR.

thanks
Sid

**Comment by sid88in** [comment]
hey @JstnEdr 

I just removed all yarn dependencies from my local and reinstalled everything and it works fine (please see below). Can you please re-clone this repo and do : yarn install to install all dependencies. Let me know if it still doesn't work?

<img width="1396" alt="screen shot 2017-11-27 at 8 10 40 pm" src="https://user-images.githubusercontent.com/1587005/33302158-1692769c-d3af-11e7-984c-c49a57124213.png">

**Comment by JstnEdr** [comment]
Thanks for the help. I tried deleting the node_modules folder and the yarn.lock file before reinstalling with `yarn install` but I'm still not getting the Playground to work. 

<img width="1440" alt="screen shot 2017-11-28 at 10 28 07 am" src="https://user-images.githubusercontent.com/385060/33331395-145e6962-d427-11e7-845e-20b340271c4c.png">

**Comment by sid88in** [comment]
@JstnEdr how about quick skype call? if you can reach out to me at https://twitter.com/sidg_sid 
we can debug it together ;)

thanks
Sid

**Comment by JstnEdr** [comment]
Playground is now loading, however the `graphql` endpoint is coming up as `undefined`. I've found and documented a workaround on issue [#287](https://github.com/graphcool/graphql-playground/issues/287) of the graphql-playground repo. Thanks @sid88in for your help and recent updates.

**Comment by sid88in** [comment]
@JstnEdr glad that helped.

**Comment by XanXus96** [comment]
@JstnEdr please how did you resolve the first problem
