### ISSUE TITLE
Authorization and Permission Handling

### ISSUE THREAD

**Issue by ac360** [serverless/serverless-graphql-apollo#20]
We're going to move the auth logic into a separate file which will be easier for people to add their own custom auth logic to.  We also need to add permission handling here, though we're not sure on the best way to do permission verification w/ GraphQL.  

Perhaps each resolve function for collections include required permissions and those are passed into the authorize method, like this: `authorize(token, requiredPermissions)`.  The JWToken can contain permissions within it.  These will be checked against the permissions hardcoded in each resolve function via an authorize method.

Do you have any thoughts on this?

cc @pmuens @minibikini @eahefnawy @breandr

**Comment by shineli1984** [comment]
When you use JWT in web context, size matters - the smaller the better. I think it maybe better to decode the jwt in authorize function and load up permissions from somewhere (database, permission file etc) then pass it as a context to graphql. Any thoughts?

**Comment by nikgraf** [comment]
Closing this since it's outdated :)
