### ISSUE TITLE
Rename project to serverless-graphql-boilerplate

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless-graphql-apollo#34]
We've renamed the project several times (and discussed this extensively) but I think that the "boilerplate" is missing in the name.

Recently I've recommended this project to another developer and he was like "Ah that's a boilerplate! At first I thought that this is a kind of extension or plugin so that GraphQL works with Serverless".
Heard similar comments about it a few times.

So I would propose to go with "serverless-graphql-boilerplate". It's a small change but I think that this makes it more accessible for starters / people who are searching for Serverless boilerplates.

**Comment by HyperBrain** [comment]
I also agree with that proposal. It would continue the naming scheme as it is used with the plugins today, e.g. serverless-XXXX-plugin.

In general all packages that extend the use or serve a certain purpose should follow the same generic naming scheme:

`serverless-{name of package}-{type of package}`

**Comment by pmuens** [comment]
@HyperBrain Good point! That makes identifying the purpose of the package way easier!

**Comment by erikerikson** [comment]
There was a really good issue in the main project asking for plugin naming
conventions to change to serverless-plugin-[name].  I think the same
ordering convention would be valuable here, allowing searches for
serverless-boilerplate in order to increase discoverability whether using a
flexible search solution or not.  It definitely supplies a better
auto-complete-style identification of the one you're looking for.

**Comment by HyperBrain** [comment]
Maybe changing the names from the already established naming scheme with plugins would be wide-breaking! All the repositories are named `serverless-[name]-plugin`so far and all users' `package.json` also contain the current scheme (not to speak of NPM).

My opinion is that adapting the current plugin naming scheme would cause the least efforts for everyone

**Comment by pmuens** [comment]
Yep. `serverless-boilerplate-[name]` would be a good convention! Haven#t thought about the auto completion but love it.

**Comment by erikerikson** [comment]
I agree Frank, it would be a bit of a pain.  That said, its only a
convention so it can be changed slowly, at will, over time for plugins.
Maybe in conjunction with the next round of breaking changes when
modifications have to happen regardless.

**Comment by HyperBrain** [comment]
Yes, that might work and the auto-completion might weight here if you even think of bash-completion etc.

**Comment by nikgraf** [comment]
Renamed it serverless-graphql-apollo and also opened up a Relay version :)
