### ISSUE TITLE
Multisite support

### ISSUE THREAD

**Issue by anddimario** [serverless/serverless-graphql-apollo#35]
Hi, what do you think about the possibility to add some sort of multisite support?
For example, it could be used an header to define the site name and use this as reference in a table fields (shared table for each site), or maybe for table name's suffix (each sites could have their table).

**Comment by nikgraf** [comment]
@anddimario sounds interesting, but most probably not something to be part of a simple boilerplate. Happy to feature it though in the Readme in case you open source such a project 🙂
