### ISSUE TITLE
TypeError: Cannot read property 'users' of undefined when running the client offline

### ISSUE THREAD

**Issue by acyuta108** [serverless/serverless-graphql-apollo#38]
I followed the installation instructions and kept getting the mentioned message in the users index page in the error box at the top. After installing redux-devtools the error is caught by it. In Firefox the message is slightly different: An error occurred: "action.payload.data is undefined". I query the endpoint and db using Graphiql and I get the data without any issues, so I know that the backend it's working.

I get this message in console (Running locally `sls offline start`) :

> Serverless: [200] {"errors":[{"message":"Syntax Error GraphQL request (1:1) Unexpected EOF\n\n1: \n   ^\n"}]}

I checked all the code and everything seem in order. I decided to add some debugging lines in the api (back/api/lib/graphql/index.js) to see the data that it was receiving, since in chrome devtools seemed the payload was fine. Then I discovered that it was receiving and "undefined" data payload!

Since I had a similar issue recently in some components I wrote in one of my projects integrating GraphQL, I added the "headers" option (setting Content-type: application/json) into the fetch request and voila! it works now. I am submitting a pull request if you reproduce the problem and find my fix to be useful.

**Comment by anddimario** [comment]
+1

**Comment by thond1st** [comment]
+1
I too have followed the installation and setup instructions but I can't seem to make it work offline.
I changed " export const API_URL = 'https://localhost:3000'; " in "client/src/app/js/actions/index.js". The amazonaws URL works but it interacts with the live DynamoDB instance. The instruction for this (API_URL) is also missing.

**Comment by nikgraf** [comment]
Closing this issue, because it's outdated and works differently in v1 :)
