### ISSUE TITLE
use SNS for sending graphql queries

### ISSUE THREAD

**Issue by swarthout** [serverless/serverless-graphql-apollo#42]
I am not sure if this would work at all, but while working on a graphql project, I noticed that the API Gateway was not really being used much for a graphql project compared to a rest project. There is only one endpoint, and caching is not as useful due to the custom requests. Also, API gateway is relatively expensive compared to other parts of the serverless stack ($3.50 per million requests). I was wondering if I could use SNS instead, with a graphql topic and a lambda controlling incoming messages.I could send requests to my lambda by publishing to the topic, then I could send a http response to the appropriate client as a message. The only reason I am considering this is because SNS is only $.60 per million requests for http, so with a large app this could save a lot of money. Would this work? Would the latency be too high? Thanks!

**Comment by jamesmcintyre** [comment]
Sounds interesting! I too would be interested if this works. If it does, I'm sure you are sacrificing a lot of control and potentially security over the endpoint but maybe certain types endpoint would be fine.

**Comment by nikgraf** [comment]
@swarthout that could work. I think the hard part is establishing and maintaining a connection to send data back to the client. AWS IoT websocket support could do that. Then you would end up with a really great event-driven architecture …
