### ISSUE TITLE
Missing Authentication Token - GraphiQL

### ISSUE THREAD

**Issue by purplecones** [serverless/serverless-graphql-apollo#43]
I'm fairly new to GraphQL in general. I followed this repo and everything works as described but when I try to user the GraphiQL app, I run into authentication issues.

![graphiql_and_new_issue_ _serverless_serverless-graphql](https://cloud.githubusercontent.com/assets/136654/15970327/19e1db60-2f02-11e6-9e9c-b07210ec37b8.png)

Where do I get the Authentication Token and how do I use it to connect to the GraphQL Endpoint?

**Comment by larsonjj** [comment]
Hey @purplecones,

I ran into the same issue. I found out (through looking at the client/frontend code) that you need to add a `/data` to the end of the url you passed in shown in your screenshot. Then you should have access to the data without the need for an auth token.

Hope this helps, cheers 🍻

**Comment by jasonbahl** [comment]
I'm getting this same error with and without adding `/data` to the url. 

I'm new to serverless so, I could be missing something. . .I've got things running fine locally, and the deploy appears to work ok, but when attemting a GET or POST request I get the same "Missing Authentication Token" message

**Comment by nikgraf** [comment]
@jasonbahl I had a similar issue in the past, but can't remember how I solved that. I will work on this boilerplate the next couple days and if I run into it I get back to you …

**Comment by aprasad123456** [comment]
Any update on the error ...Even I am also getting the same error when trying to connect an AWS RDS client

**Comment by nikgraf** [comment]
I didn't run into that issue since then. Sorry @aprasad123456

**Comment by goocastro** [comment]
Same error here.
I'm running the example application with

    functions:
      index:
        handler: handler.hello
        events:
          - http: GET hello

It generates me an URL which returns only

    message	"Missing Authentication Token"

Not the json I get from running the app on terminal

**Comment by nickwood2009** [comment]
Any updates on this? I am getting the exact same issue

**Comment by joshhornby** [comment]
I too am having this issue, any updates on what the token should be?

**Comment by EmiPC** [comment]
Same issue here...

**Comment by markfranco** [comment]
Hey guys, was having this issue the pass hour.

```
functions:
  api:
    handler: graphql/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
          integration: lambda-proxy

  graphiql:
    handler: graphql/handler.graphiqlHandler
    events:
      - http:
          path: graphiql
          method: get
          cors: true
          integration: lambda-proxy
```

I was testing this in Postman, and if I was trying to make a Get request on the path grapghql, it would throw me that error of "Missing Authentication Token". So if method doesn't exist that's the error you would more likely to see.

I had to look into cloud watch and it gives me a more descriptive message.

After logging everywhere I notice the code given on [NPM](https://www.npmjs.com/package/graphql-server-lambda#modify-the-lambda-response-enable-cors) to enable CORS, in const callbackFilter the output object didn't have a headers property. I ended up just modifying the headers object on event since it was present there.

Here is the code that eventually made it work for me. Just had to configure the endpointUrl to the setting in serverless.yml.

```
var server = require("apollo-server-lambda");
var schema = require('./schema');

exports.graphqlHandler = function(event, context, callback) {
    const callbackFilter = function(error, output) {
        callback(error, output);
    };

    event.headers['Access-Control-Allow-Origin'] = '*';
    event.headers['Access-Control-Allow-Credentials'] = true;

    const handler = server.graphqlLambda({ schema });

    return handler(event, context, callbackFilter);

}

exports.graphiqlHandler = function(event, context, callback) {
    const handler = server.graphiqlLambda({
	    endpointURL: '/dev/graphql'
    });

    return handler(event, context, callback);
}

```

**Comment by scotttesler** [comment]
@markfranco Didn't work for me :/

**Comment by sid88in** [comment]
https://github.com/serverless/serverless-graphql-apollo/pull/111 should address all of this. 

Closing this issue.
