### ISSUE TITLE
Error running offline: Syntax Error GraphQL request (1:1) Unexpected EOF

### ISSUE THREAD

**Issue by ericvera** [serverless/serverless-graphql-apollo#45]
I ran into this issue when trying to work offline (both backend and front end). I was able to fix the issue by adding the content-type header. I see that this project is not using the latest version of serverless-offline and a change there could possibly address the issue. Otherwise the simple fix below would also unblock.

Before (not working):

```
return (dispatch) => fetch(`${API_URL}/data/`, {
    method: 'POST',
    body: JSON.stringify(query)
  }).then(...
```

After (working):

```
  var testHeaders = new Headers();
  testHeaders.append("Content-Type", "application/json");

  return (dispatch) => fetch(`${API_URL}/data/`, {
    method: 'POST',
    body: JSON.stringify(query),
    headers: testHeaders
  })
  .then(...
```

Error:

```
Serverless: POST /data (λ: data)  
Serverless: [200] {"errors":[{"message":"Syntax Error GraphQL request (1:1) Unexpected EOF\n\n1: \n   ^\n"}]}
```

**Comment by darthtrevino** [comment]
I ran into this issue on a fresh installation, and it ended up being because the JSON payloads were being sent to the lambda function as "[Object object]". I had to update s-function.json

"requestTemplates": {
  ~~"application/json": "{\"query\" : $input.json(\"$\")}"~~
  "application/json": "{\"query\" : $input.body}"
},

**Comment by samueljamesmarshall** [comment]
In my experience, this problems occurs when the event body is not parsed as JSON e.g.
```javascript
{
  ...
  "body": "{\"query\": \"{ viewer { name } }\"}",
  ...
}
```
An easy fix to this problem is to parse the event body in your [handler].js file before passing it to graphql:
```javascript
exports.graphql = (event, context, callback) => {
  event.body = JSON.parse(event.body);
  
  ...
};
```
The above will fix the event body, resulting in the following:
```javascript
{
  ...
  "body": {
    "query": "{ viewer { name } }"
  },
  ...
}
```
:)

**Comment by nikgraf** [comment]
From what I understood this is a legacy issue. Let me know if this still occurs …
