### ISSUE TITLE
feature req: include cognito authentication

### ISSUE THREAD

**Issue by gebrits** [serverless/serverless-graphql-apollo#48]
Would love to see this boilerplate containing working setup for cognito userpools and/or cognito federated identities.

Would you consider this to be in scope?

**Comment by pmuens** [comment]
Hey @gebrits thanks for the feedback and the great idea!

We're currently working on Serverless v1 (see: https://github.com/serverless/serverless/tree/v1.0) and plan to update the projects we have so that they run v1. We'll consider this when we start the work on the GraphQL boilerplate.

**Comment by gebrits** [comment]
cheers. Looking forward!

**Comment by nikgraf** [comment]
@gebrits we shipped it about 3 months ago. let me know what you think 👍
