### ISSUE TITLE
QUESTION: Any plans to support databases other than DynamoDB?

### ISSUE THREAD

**Issue by janaka** [serverless/serverless-graphql-apollo#49]

**Comment by pmuens** [comment]
Hey @janaka thank you for your questions!
We're currently working on Serverless v1 and are about to update our old repos. We'll consider your feedback when we start the update process for this one (PRs are welcomed! :-))

**Comment by nikgraf** [comment]
@janaka we shipped a version for v1 a couple months back, I'm curious what you think about it 👍

**Comment by janaka** [comment]
Hi Nik, I'm personally not working on anything Lambda related at the moment but have been following the release at a feature level. Those I know who have been using it have been pretty happy with improvements. Also loving the pace of release. Keep up the good work.

**Comment by nikgraf** [comment]
Thanks @janaka
