### ISSUE TITLE
Python Equivalent for Serverless GraphQL

### ISSUE THREAD

**Issue by kfloz** [serverless/serverless-graphql-apollo#60]
Hi great stuff!  Loving learning grpahQL.

Will there be a python boiler plate equiv with Graphene and other similar libraries?

Thanks and nice work. :)

**Comment by nikgraf** [comment]
@kfloz I hope so at some point. For the time being I need to focus on other things. If you are interested to help out here let me know 😄

**Comment by nikgraf** [comment]
Closing this for now so the issues are easier to manage! Still would love to see a python version though :)
