### ISSUE TITLE
What platform does this project support?

### ISSUE THREAD

**Issue by joshg111** [serverless/serverless-graphql-apollo#62]
Does this project work with windows? What is the recommended platform?

**Comment by nikgraf** [comment]
@joshg111 to be honest I haven't tried yet. I would assume it does, but need to check some of the package.json files to do so. Do you have a windows machine and want to use it?

**Comment by joshg111** [comment]
@nikgraf I just setup an Ubuntu station, I will try with that since it didn't seem to work with windows. Out of curiosity what platform would you recommend in general and what platform would you recommend for using serverless?

**Comment by nikgraf** [comment]
@joshg111 serverless itself should work with any platform e.g. Linux, OSX, Windows. We just have been in a rush carving out the boilerplate and it wasn't one of my top priorities. Eventually also this starterkit/boilerplate should work on Window.s

**Comment by beckeste** [comment]
Works with windows if you use the npm package "cross-env" (npm install -S cross-env), and change  "MOCKED_DATABASE=true" to "cross-env MOCKED_DATABASE=true" in the package.json.

**Comment by getglad** [comment]
I can confirm @beckeste fix

**Comment by getglad** [comment]
I also had to change `cp ./app/favicon.ico ./build/frontend/favicon.ico` to `copy ./app/favicon.ico ./build/frontend/favicon.ico` on Windows. (I am also getting an "The syntax of the command is incorrect." when building the front end, but I think that is related to build issues, not Windows).

**Comment by nikgraf** [comment]
@beckeste interested to create a PR with the fix?

**Comment by getglad** [comment]
@nikgraf I can submit a PR - it's a simple fix on Win10, if you can test on Mac OS

**Comment by EmiPC** [comment]
@beckeste or @getglad, did you make this project work on Windows? I've did several changes but I'm still getting several errors when doing "npm run deploy".

**Comment by EmiPC** [comment]
Well, I've solved it by adding C:\Program Files\Git\usr\bin to my %PATH% and the issue disappeared (it adds support for commands not supported, like "cp").
