### ISSUE TITLE
Explanation of project

### ISSUE THREAD

**Issue by johncmckim** [serverless/serverless-graphql-apollo#63]
Whenever I look at a boilerplate project, the three questions I always have are 'What is this?', 'Where is everything?' and 'What parts do I need to implement?'.

It would be awesome if those questions were explicitly answered in the `README`.  To help answer those questions, it could be helpful to have a simple diagram to show the architecture of the project. [draw.io](https://www.draw.io/) is a good free diagram tool.

Thoughts?

**Comment by nikgraf** [comment]
100% agree! I try to create some explanatory texts + diagrams in the next 2 weeks.

**Comment by nikhilag** [comment]
@nikgraf Did you get a chance to work on the text and diagrams?

**Comment by sid88in** [comment]
@johncmckim hopefully https://github.com/serverless/serverless-graphql-apollo/pull/102 resolves this issue to certain extent. We have added new diagrams etc.

**Comment by sid88in** [comment]
@johncmckim we have updated README with comprehensive explanations and diagrams. Feel free to contribute more ;)
