### ISSUE TITLE
The specified bucket does not exist 

### ISSUE THREAD

**Issue by Danjavia** [serverless/serverless-graphql-apollo#72]
Please help me. I try to deploy serverless but this error appear when try to excecute 

```
serverless --stage=production deploy 
```
into **npm run deploy:api** step

here is the cli output

```
Serverless Error ---------------------------------------

     The specified bucket does not exist

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.2.0
     Serverless Version: 1.4.0
```

**Comment by kmjennison** [comment]
This can happen if you manually delete the S3 bucket rather than deleting it via Serverless/CloudFormation. See: https://github.com/serverless/serverless/issues/1877

**Comment by nikgraf** [comment]
thanks for jumping in here and helping out @kmjennison 🙇

**Comment by Danjavia** [comment]
Not now :( I'm try again form zero but nothing happens. Thanks guys!

**Comment by nikgraf** [comment]
@Danjavia what do you mean by nothing happens?

**Comment by Danjavia** [comment]
I have the same issue. And checking in s3 the bucket exists correctly. I don't know.

**Comment by nikgraf** [comment]
hey @Danjavia - sorry for getting back so late. Did you eventually resolve the issue?

**Comment by realadeel** [comment]
Try deleting the stack from CloudFormation and redeploying - that got me over this hump.

**Comment by sshadmand** [comment]
Something is definitely off here. Using the same serverless.yml, and as a test, I was able to create the deployment, then used `serverless remove` successfully. Then, I ran deploy again and got failures. There is definitely a clean up issue.

**Comment by shashanktomar** [comment]
Deleting the cloudformation template might not be a good solution. The next deployment will create a new api-gateway deployment with different id, which will change the url(might not matter if you are using cnames).
The better solution which worked for me was:

go to cloudtrail and select s3 resource to check the deleted bucket name. You don't need this if you have some other way of knowing the bucket name.
create a bucket with same name.
retrigger deployment
Looks like serverless use the bucket just for backup. It worked for me.

**Comment by jleppert** [comment]
This is just a general comment but when you deliver back error messages to the user, please try to include the proper name of what doesn't exist. That is, if a bucket doesn't exist you should say WHAT THE BUCKET NAME IS.

Also, passing `--verbose` does nothing. A command line tool is supposed to be a user interface, not a hurdle.

**Comment by derwaldgeist** [comment]
> Try deleting the stack from CloudFormation and redeploying
This worked for me, too. Thanks.

**Comment by jelder** [comment]
I would like to reopen this issue. It is fairly easy to arrive at this situation and this has happened to me numerous times over the past few months. I've never been able to identify exactly how to fix it. The error message Serverless yields is useless. At the very minimum, the bucket name needs to be included in the error.

**Comment by Chanonry** [comment]
I agree the error messages are poor. When it has happened to me it has usually been when I have been using plugins to simplify the removal of the stack. It is rare though.

Best approach was above - look at Cloudtrail. It seems to be the removal of the serverless bucket itself that causes the problem. As its not named in the yaml file your attention is not directed to it.

**Comment by chenrui333** [comment]
It would be really valuable that the bucket name is included in the error message.

**Comment by ahallora** [comment]
I had deleted the s3 bucket long ago and was getting `Unhandled rejection ServerlessError: The specified bucket does not exist`. The cloudtrail was too old to show the bucket name.

I did `sls info -v -s prod` and found the **ServerlessDeploymentBucketName** ... 👍
