### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by andreafalzetti** [serverless/serverless-graphql-apollo#77]
I've just cloned this repo on my machine, following the docs int he readme I've installed all dependencies using yarn and started the application with npm, the `api/config.js` file is generated, but straight after that the app crashes because of the following:

```
throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
                ^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'progress'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           progress: ...
         }
       })
     ]
 - configuration.resolve has an unknown property 'packageMains'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (/....../serverless-graphql-apollo/node_modules/webpack/lib/webpack.js:19:9)
    at Object.<anonymous> (/....../serverless-graphql-apollo/foundation/devServer/index.js:13:18)
    at Module._compile (module.js:570:32)
    at loader (/....../serverless-graphql-apollo/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/....../serverless-graphql-apollo/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at /....../serverless-graphql-apollo/node_modules/babel-cli/lib/_babel-node.js:159:24
    at Object.<anonymous> (/....../serverless-graphql-apollo/node_modules/babel-cli/lib/_babel-node.js:160:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[nodemon] app crashed - waiting for file changes before starting...
```

Any idea of what is wrong?

**Comment by gwhobbs** [comment]
I am getting the same error.

**Comment by jthegedus** [comment]
I am also having this issue. It might be due to using Webpack 2 (of which v2.2 just released https://github.com/webpack/webpack/releases/tag/v2.2.0 ) but with errors in the webpack.base.js config during updating.

**Comment by mpigsley** [comment]
I tried to get this to work. I followed the [migration guide](https://webpack.js.org/guides/migrating/) and [was able to make webpack happy again](https://github.com/serverless/serverless-graphql-apollo/compare/master...mpigsley:webpack-2).

The webpack errors are gone but I'm still seeing some non-specific errors when I try to load it up in the browser. I'll try to circle back around today and get this working.

**Comment by jthegedus** [comment]
@mpigsley It works for me with your changes. I just pulled your webpack-2 branch and it ran fine. The only issue now is that the Webpack bundle isn't loading into the index.html. Again, I'm new to Webpack so am not clear where the error may be or if this is user error.

`api/config.js file was generated
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node ./foundation/devServer`
App is now running on http://localhost:3000
webpack built 379cefe96df7c0017dae in 3411ms
2017-01-21T03:26:41.634Z 'GET' '/'
2017-01-21T03:26:41.657Z 'GET' '/main.js'
2017-01-21T03:26:42.023Z 'GET' '/__webpack_hmr'
2017-01-21T03:26:42.074Z 'GET' '/favicon.ico'`

**Comment by juhaelee** [comment]
@mpigsley did you ever figure out how to fix that issue?

**Comment by juhaelee** [comment]
@mpigsley found out what the problem was, I guess webpack2 doesn't like nested values in `DefinePlugin`

If you change your define plugin to:
```
new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
      'process.env.GRAPHQL_ENDPOINT': process.env.URL,
}),
```

all should be well 👍

**Comment by mpigsley** [comment]
Ahh, right you are @juhaelee !

I haven't been around this project long. Is this what it's supposed to look like?

<img width="1439" alt="screen shot 2017-01-21 at 12 12 45 pm" src="https://cloud.githubusercontent.com/assets/3017491/22176546/0769c8bc-dfd3-11e6-92fd-5c18c6f88772.png">

In the meantime, I'll get a PR up.

**Comment by mpigsley** [comment]
Looks like moving postcss configuration in a `postcss.config.js` file in the root directory fixed the styling errors ^

**Comment by jthegedus** [comment]
@mpigsley That looks right to me (at least from the last stable build I tried a couple weeks ago).

**Comment by andreafalzetti** [comment]
Amazing. Thanks guys!!
