### ISSUE TITLE
classnames in html file not correct

### ISSUE THREAD

**Issue by sixtatami** [serverless/serverless-graphql-apollo#81]
it seems the webpack is not including the class names correclty in the html. I can only guess that the HtmlWebpackPlugin is doing something wrong with the html. cant figure it out myself though

**Comment by andreimc** [comment]
hey @sixtatami I provided a PR that fixes this. I couldn't figure out the root cause, I believe it was something to do with packages

**Comment by nikgraf** [comment]
Thanks @andreimc 👏
