### ISSUE TITLE
"Use mocked data" & "Use live data from the development environment"

### ISSUE THREAD

**Issue by nfurfaro** [serverless/serverless-graphql-apollo#82]
I've managed to get this starter kit up and running fine. I can view locally using 
`npm start` 
and after deploying twice with 
`npm run deploy`
 I'm able to see the live site using the new url with my bucket name.
`npm run start:remote` works fine as well at localhost3000.

My question is:
How can I change the data displayed? I've tried changing the name "Ada Lovelace" everywhere I can find it (in both mocked database and database) but it doesn't have any effect upon reloading the browser.

**Comment by ctwhome** [comment]
![image](https://cloud.githubusercontent.com/assets/4195550/24828598/b4dc1bac-1c60-11e7-877f-70c9a7baf473.png)

**Comment by nikgraf** [comment]
@nfurfaro did the screenshot from @ctwhome help?

**Comment by nfurfaro** [comment]
Yes it did, and so sorry for not replying in a timely manner. Bad form on my part!
