### ISSUE TITLE
(On NPM Run Deploy) ServerlessError: not a valid key=value pair (missing equal-sign) in Authorization

### ISSUE THREAD

**Issue by SuttJ** [serverless/serverless-graphql-apollo#83]
<img width="909" alt="screen shot 2017-02-22 at 6 40 18 pm" src="https://cloud.githubusercontent.com/assets/16503197/23238136/8a8ae144-f92e-11e6-870a-21ee784b0874.png">

**Comment by nikgraf** [comment]
😕 I haven't seen an error like that so far. @SuttJ did you eventually solve the issue?
