### ISSUE TITLE
build:api not including any graphql files

### ISSUE THREAD

**Issue by getglad** [serverless/serverless-graphql-apollo#92]
This may be [another Windows only](https://github.com/serverless/serverless-graphql-apollo/issues/62) issue because no one else has reported it, but 

`build:api": "npm run generate:config:prod && cross-env NODE_ENV=production babel --out-dir='api/graphql' --ignore='__tests__/*' ./graphql`

Results in my `graphql` folder being built into `'api/graphql'/...` instead of `api/graphql/...`, thus not getting zipped and sent to S3.

Dropping the single quotes around the `--out-dir` path resolves the issue:

`build:api": "npm run generate:config:prod && cross-env NODE_ENV=production babel --out-dir=api/graphql --ignore='__tests__/*' ./graphql`

**Comment by nikgraf** [comment]
any suggestions how to fix it? I'm not too familiar with Windows.

**Comment by getglad** [comment]
I can submit a PR - it's a simple fix on Win10, if you can test on Mac OS

**Comment by EmiPC** [comment]
Did you manage to solve this incompatibility with windows?

**Comment by sid88in** [comment]
@getglad going to close this issue. The code base has changed. Feel free to re-open the issue if you still see it.
