### ISSUE TITLE
'MOCKED_DATABASE' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by flieks** [serverless/serverless-graphql-apollo#93]
Hi,

I cloned and installed the stuff (yarn), all went well. 
Then `npm start`
right after
`api/config.js file was generated`
i get that error..
`'MOCKED_DATABASE' is not recognized as an internal or external command`

**Comment by nikgraf** [comment]
@flieks which operating system are you on?

**Comment by peXed** [comment]
@nikgraf hello. I get the same error and I am on Windows.

**Comment by MeixnerTobias** [comment]
@flieks @peXed 
The command won't work in Windows so you either move MOCKED_DATABASE into webpack or
> 
npm install --save-dev cross-env

and then change start command in package.json to:
>
"start": "npm run generate:config:local && cross-env MOCKED_DATABASE=true env-cmd foundation/environment/security.env.local nodemon ./foundation/devServer --ignore app --exec babel-node",

**Comment by sid88in** [comment]
invalid with new code base https://github.com/serverless/serverless-graphql-apollo/pull/102
