### ISSUE TITLE
Resolver for GraphQLList?

### ISSUE THREAD

**Issue by VinzentE** [serverless/serverless-graphql-apollo#98]
Sweet contribution! I have most of it up and running and am loving the setup.

I did manage to **add several type definitions**. Now I wanted to move on to the **resolvers**, but got stuck:
I do understand the "viewer" resolver - thanks to the great example within the boilerplate. 
Now i have added a couple of other fields below the viewer:{...} within query.js - some of them are **ListTypes** - e.g. `samples: {type: new GraphQLList(Sample)}`.

**3 questions**:
* **Where to add** the resolver: within samples or in the Sample-Type Definition?
* **What** would a **resolver for a GraphQLList** Type **look like**?
* **How to integrate** it within the **mockedDatabase/index.js**?

Really appreciate any help ... 
Thanks

**Comment by sid88in** [comment]
@VinzentE we have changed the code base introduced Apollo Lambda Server (deprecated GraphQL-js). You can see example in resolvers.js and see how its integrated in handler.js https://github.com/serverless/serverless-graphql-apollo/pull/102
